name: Deploy Cloud Function
on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy YOUR_FUNCTION_NAME --runtime nodejs16 --trigger-http --source=./ --entry-point=YOUR_ENTRY_POINT --region=YOUR_REGION